export const ProductData = [
  {
    id: 0,
    name: '오메가메이트',
    property: '760mg 2캡슐',
    thumbImage: '/images/product-bio.png',
    content: ['혈행 개선에 도움', '기억력 개선', '눈 건강 개선에 도움'],
    price: '7,500',
    listPrice: '9,000',
  },
  {
    id: 1,
    name: '루테인메이트',
    property: '150mg 1캡슐',
    thumbImage: '/images/product-lutein.png',
    content: ['눈 건강 개선에 도움'],
    price: '7,500',
    listPrice: '9,000',
  },
  {
    id: 2,
    name: '프로바이옴메이트',
    property: '300mg 1캡슐',
    thumbImage: '/images/product-lutein.png',
    content: ['유익균 증식과 유해균 억제', '장건강 개선'],
    price: '7,500',
    listPrice: '9,000',
  },
  {
    id: 3,
    name: '코엔자임메이트',
    property: '300mg 1정',
    thumbImage: '/images/product-Q10.png',
    content: ['고혈압 개선에 도움', '힝산화 효과'],
    price: '7,500',
    listPrice: '9,000',
  },
  {
    id: 4,
    name: '마그네슘메이트',
    property: '1000mg 1정',
    thumbImage: '/images/product-magnesium.png',
    content: ['인체 에너지 이용', '신경과 근육 기능 유지에 필요'],
    price: '7,500',
    listPrice: '9,000',
  },
  {
    id: 5,
    name: '테아닌메이트',
    property: '1000mg 1정',
    thumbImage: '/images/product-theanine.png',
    content: ['긴장 완화에 도움'],
    price: '7,500',
    listPrice: '9,000',
  },
]
